- project:
    name: openstack/tooz
    check:
      jobs:
        - tooz-tox-py27-etcd
        - tooz-tox-py35-etcd:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-etcd3:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py35-etcd3:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py27-etcd3gw:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py35-etcd3gw:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py27-zookeeper
        - tooz-tox-py35-zookeeper:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-redis
        - tooz-tox-py35-redis:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-sentinel
        - tooz-tox-py35-sentinel:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-memcached
        - tooz-tox-py35-memcached:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-postgresql
        - tooz-tox-py35-postgresql:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-mysql
        - tooz-tox-py35-mysql:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-consul
        - tooz-tox-py35-consul:
            branches: ^(?!stable/newton).*$
    gate:
      jobs:
        - tooz-tox-py27-etcd
        - tooz-tox-py35-etcd:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-etcd3:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py35-etcd3:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py27-etcd3gw:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py35-etcd3gw:
            branches: ^(?!stable/(newton|ocata)).*$
        - tooz-tox-py27-zookeeper
        - tooz-tox-py35-zookeeper:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-redis
        - tooz-tox-py35-redis:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-sentinel
        - tooz-tox-py35-sentinel:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-memcached
        - tooz-tox-py35-memcached:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-postgresql
        - tooz-tox-py35-postgresql:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-mysql
        - tooz-tox-py35-mysql:
            branches: ^(?!stable/newton).*$
        - tooz-tox-py27-consul
        - tooz-tox-py35-consul:
            branches: ^(?!stable/newton).*$

- job:
    name: tooz-tox-py27-consul
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-consul/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-consul/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-etcd
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-etcd/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-etcd/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-etcd3
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-etcd3/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-etcd3/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-etcd3gw
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-etcd3gw/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-etcd3gw/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-memcached
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-memcached/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-memcached/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-mysql
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-mysql/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-mysql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-postgresql
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-postgresql/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-postgresql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-redis
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-redis/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-redis/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-sentinel
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-sentinel/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-sentinel/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py27-zookeeper
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py27-zookeeper/run.yaml
    post-run: playbooks/legacy/tooz-tox-py27-zookeeper/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-consul
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-consul/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-consul/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-etcd
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-etcd/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-etcd/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-etcd3
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-etcd3/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-etcd3/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-etcd3gw
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-etcd3gw/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-etcd3gw/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-memcached
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-memcached/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-memcached/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-mysql
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-mysql/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-mysql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-postgresql
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-postgresql/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-postgresql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-redis
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-redis/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-redis/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-sentinel
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-sentinel/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-sentinel/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: tooz-tox-py35-zookeeper
    parent: legacy-base
    run: playbooks/legacy/tooz-tox-py35-zookeeper/run.yaml
    post-run: playbooks/legacy/tooz-tox-py35-zookeeper/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements
